python3 feature_reading.py --datasets "cifar10" --trail 2 --size 32 --model "resnet_multi" --model_path "/save/SupCon/cifar10_models/cifar10_resnet_multi_trail_2_128_0.05_256/last.pth" --if_train "train" --method 'multi_head' --feature_save "/features/"
python3 feature_reading.py --datasets "cifar10" --trail 2 --size 32 --model "resnet_multi" --model_path "/save/SupCon/cifar10_models/cifar10_resnet_multi_trail_2_128_0.05_256/last.pth" --if_train "test_known" --method 'multi_head' --feature_save "/features/"
python3 feature_reading.py --datasets "cifar10" --trail 2 --size 32 --model "resnet_multi" --model_path "/save/SupCon/cifar10_models/cifar10_resnet_multi_trail_2_128_0.05_256/last.pth" --if_train "test_unknown" --method 'multi_head' --feature_save "/features/"


python3 feature_reading.py --datasets "cifar10" --trail 3 --size 32 --model "resnet_multi" --model_path "/save/SupCon/cifar10_models/cifar10_resnet_multi_trail_2_128_0.05_256/last.pth" --if_train "train" --method 'multi_head' --feature_save "/features/"
python3 feature_reading.py --datasets "cifar10" --trail 3 --size 32 --model "resnet_multi" --model_path "/save/SupCon/cifar10_models/cifar10_resnet_multi_trail_2_128_0.05_256/last.pth" --if_train "test_known" --method 'multi_head' --feature_save "/features/"
python3 feature_reading.py --datasets "cifar10" --trail 3 --size 32 --model "resnet_multi" --model_path "/save/SupCon/cifar10_models/cifar10_resnet_multi_trail_2_128_0.05_256/last.pth" --if_train "test_unknown" --method 'multi_head' --feature_save "/features/"

python3 feature_reading.py --datasets "cifar10" --trail 4 --size 32 --model "resnet_multi" --model_path "/save/SupCon/cifar10_models/cifar10_resnet_multi_trail_4_128_0.005_0.01_0.05_256/last.pth" --if_train "train" --method 'multi_head' --feature_save "/features/"
python3 feature_reading.py --datasets "cifar10" --trail 4 --size 32 --model "resnet_multi" --model_path "/save/SupCon/cifar10_models/cifar10_resnet_multi_trail_4_128_0.005_0.01_0.05_256/last.pth" --if_train "test_known" --method 'multi_head' --feature_save "/features/"
python3 feature_reading.py --datasets "cifar10" --trail 4 --size 32 --model "resnet_multi" --model_path "/save/SupCon/cifar10_models/cifar10_resnet_multi_trail_4_128_0.005_0.01_0.05_256/last.pth" --if_train "test_unknown" --method 'multi_head' --feature_save "/features/"